language: cpp
env:
    - ATUTILS_ARCH=32
    - ATUTILS_ARCH=64
compiler:
    - gcc
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:boost-latest/ppa
    - sudo apt-get -qq update
install:
    - sudo apt-get install g++-4.8-multiarch && export CXX=g++-4.8 && export CC=gcc-4.8
    - sudo apt-get install libboost-test1.55-dev
script:
    - CXXFLAGS="-m$ATUTILS_ARCH" cmake .
    - make
    - make check
