language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu/ quantal main"
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:boost-latest/ppa
    - sudo apt-get -qq update
install:
    - 'if [ $CXX = "clang++" ]; then sudo apt-get install g++; fi'
    - 'if [ $CXX = "g++" ]; then sudo apt-get install g++-4.8 && export CXX=g++-4.8 && export CC=gcc-4.8; fi'
    - sudo apt-get install libboost-test1.55-dev
script:
    - cmake .
    - make
    - make check
